module errno

pub enum Errno {
	EPERM        = C.EPERM
	ENOENT       = C.ENOENT
	ESRCH        = C.ESRCH
	EINTR        = C.EINTR
	EIO          = C.EIO
	ENXIO        = C.ENXIO
	E2BIG        = C.E2BIG
	ENOEXEC      = C.ENOEXEC
	EBADF        = C.EBADF
	ECHILD       = C.ECHILD
	EAGAIN       = C.EAGAIN
	ENOMEM       = C.ENOMEM
	EACCES       = C.EACCES
	EFAULT       = C.EFAULT
	EBUSY        = C.EBUSY
	EEXIST       = C.EEXIST
	EXDEV        = C.EXDEV
	ENODEV       = C.ENODEV
	ENOTDIR      = C.ENOTDIR
	EISDIR       = C.EISDIR
	ENFILE       = C.ENFILE
	EMFILE       = C.EMFILE
	ENOTTY       = C.ENOTTY
	EFBIG        = C.EFBIG
	ENOSPC       = C.ENOSPC
	ESPIPE       = C.ESPIPE
	EROFS        = C.EROFS
	EMLINK       = C.EMLINK
	EPIPE        = C.EPIPE
	EDOM         = C.EDOM
	EDEADLK      = C.EDEADLK
	ENAMETOOLONG = C.ENAMETOOLONG
	ENOLCK       = C.ENOLCK
	ENOSYS       = C.ENOSYS
	ENOTEMPTY    = C.ENOTEMPTY

	// Error codes used in the Secure CRT functions
	// Defined only when no RC_INVOKED is defined.
	EINVAL = C.EINVAL
	ERANGE = C.ERANGE
	EILSEQ = C.EILSEQ

	// STRUNCATE = C.STRUNCATE
	// Backward compatibility with older Microsoft C versions
	EDEADLOCK = C.EDEADLK

	// Next nums defined only when no _CRT_NO_POSIX_ERROR_CODES is defined
	EADDRINUSE      = C.EADDRINUSE
	EADDRNOTAVAIL   = C.EADDRNOTAVAIL
	EAFNOSUPPORT    = C.EAFNOSUPPORT
	EALREADY        = C.EALREADY
	EBADMSG         = C.EBADMSG
	ECANCELED       = C.ECANCELED
	ECONNABORTED    = C.ECONNABORTED
	ECONNREFUSED    = C.ECONNREFUSED
	ECONNRESET      = C.ECONNRESET
	EDESTADDRREQ    = C.EDESTADDRREQ
	EHOSTUNREACH    = C.EHOSTUNREACH
	EIDRM           = C.EIDRM
	EINPROGRESS     = C.EINPROGRESS
	EISCONN         = C.EISCONN
	ELOOP           = C.ELOOP
	EMSGSIZE        = C.EMSGSIZE
	ENETDOWN        = C.ENETDOWN
	ENETRESET       = C.ENETRESET
	ENETUNREACH     = C.ENETUNREACH
	ENOBUFS         = C.ENOBUFS
	ENODATA         = C.ENODATA
	ENOLINK         = C.ENOLINK
	ENOMSG          = C.ENOMSG
	ENOPROTOOPT     = C.ENOPROTOOPT
	ENOSR           = C.ENOSR
	ENOSTR          = C.ENOSTR
	ENOTCONN        = C.ENOTCONN
	ENOTRECOVERABLE = C.ENOTRECOVERABLE
	ENOTSOCK        = C.ENOTSOCK
	ENOTSUP         = C.ENOTSUP
	EOPNOTSUPP      = C.EOPNOTSUPP
	EOVERFLOW       = C.EOVERFLOW
	EOWNERDEAD      = C.EOWNERDEAD
	EPROTO          = C.EPROTO
	EPROTONOSUPPORT = C.EPROTONOSUPPORT
	EPROTOTYPE      = C.EPROTOTYPE
	ETIME           = C.ETIME
	ETIMEDOUT       = C.ETIMEDOUT
	ETXTBSY         = C.ETXTBSY
	EWOULDBLOCK     = C.EWOULDBLOCK
	// TODO: not defined
	// EOTHER = C.EOTHER
}
